"""A tiny explicit state graph: named nodes, declared edges, one async step at a time.

There is no agent framework here for the same reason there is no RAG framework (see ``app/rag``):
the whole engine is ~90 lines, so every transition is inspectable and unit-testable, and the
diagram in the README is generated by ``to_mermaid`` from the very definition the service runs —
it cannot drift from the behaviour.

Two rules keep a run bounded, which is what makes an agent safe to expose over HTTP:

* **Declared edges.** A node may only move to a target its edges list, so a prompt (or a model
  hallucinating a step name) can never send the run somewhere the graph does not allow.
* **A step budget.** Cycles are legal and useful (critique -> revise -> critique), so the run stops
  at ``max_steps`` rather than trusting a node to end it.
"""

import time
from collections.abc import Awaitable, Callable, Mapping, Sequence
from dataclasses import dataclass
from typing import Generic, TypeVar

END = "end"

S = TypeVar("S")


@dataclass(frozen=True)
class Next:
    """What a node decided: the node to run next (or ``END``), and a note for the trace."""

    node: str
    note: str | None = None


@dataclass(frozen=True)
class Step:
    """One completed transition, reported in the API response and to the tracer."""

    node: str
    next: str
    duration_ms: float
    note: str | None = None


Node = Callable[[S], Awaitable[Next]]


class GraphError(RuntimeError):
    """A node moved somewhere its edges don't allow, or the graph is malformed."""


class StepBudgetExceeded(RuntimeError):
    """The run hit ``max_steps``: a cycle that never settled."""


@dataclass
class Graph(Generic[S]):
    nodes: Mapping[str, Node[S]]
    edges: Mapping[str, Sequence[str]]
    entry: str
    max_steps: int = 12
    name: str = "agent"

    def __post_init__(self) -> None:
        if self.entry not in self.nodes:
            raise GraphError(f"entry node {self.entry!r} is not defined")
        if set(self.edges) != set(self.nodes):
            missing = set(self.nodes) ^ set(self.edges)
            raise GraphError(f"every node needs declared edges; check {sorted(missing)}")
        for node, targets in self.edges.items():
            unknown = [t for t in targets if t != END and t not in self.nodes]
            if unknown:
                raise GraphError(f"{node} points at undefined node(s) {unknown}")
            if not targets:
                raise GraphError(f"{node} has no outgoing edges, not even {END}")

    async def run(self, state: S, *, on_step: Callable[[Step], None] | None = None) -> list[Step]:
        steps: list[Step] = []
        current = self.entry
        while current != END:
            if len(steps) >= self.max_steps:
                raise StepBudgetExceeded(
                    f"{self.name} did not finish within {self.max_steps} steps"
                )
            start = time.perf_counter()
            decision = await self.nodes[current](state)
            if decision.node not in self.edges[current]:
                raise GraphError(
                    f"{current} tried to move to {decision.node!r}, "
                    f"which is not one of {list(self.edges[current])}"
                )
            step = Step(
                node=current,
                next=decision.node,
                duration_ms=round((time.perf_counter() - start) * 1000, 2),
                note=decision.note,
            )
            steps.append(step)
            if on_step is not None:
                on_step(step)
            current = decision.node
        return steps

    def to_mermaid(self) -> str:
        """The graph as a Mermaid flowchart, generated from the edges above."""
        lines = ["flowchart TD", f"    start([start]) --> {self.entry}"]
        for node, targets in self.edges.items():
            for target in targets:
                if target == END:
                    lines.append(f"    {node} --> done([done])")
                else:
                    lines.append(f"    {node} --> {target}")
        return "\n".join(lines)
